#!/usr/bin/env bash
# AppImage builder for Melete (Phase 7.5, #43).
#
# Assembles an AppDir, then wraps it with `linuxdeploy` + the GTK
# plugin so libgtk-4 / libadwaita / cairo / pango / pixbuf / poppler /
# vulkan loader are all bundled inside the final .AppImage.
#
# Inputs:
#   - target/release/melete-app  (pre-built; built by the CI step
#     before calling this script)
#   - resources/app.melete.desktop
#   - resources/icons/app.melete.svg
#
# Outputs:
#   - dist/Melete-${VERSION}-x86_64.AppImage
#
# Env vars (optional):
#   VERSION   — version string baked into the filename; defaults to
#               the value of `git describe --tags --always`.
#   ARCH      — `x86_64` (default) or `aarch64` for the ARM build.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd)"
cd "${REPO_ROOT}"

ARCH="${ARCH:-x86_64}"
VERSION="${VERSION:-$(git describe --tags --always 2>/dev/null || echo dev)}"
DIST="${REPO_ROOT}/dist"
APPDIR="${DIST}/AppDir"

if [[ ! -x target/release/melete-app ]]; then
    echo "error: target/release/melete-app missing — run cargo build --release first" >&2
    exit 1
fi

# Clean previous AppDir so a stale layout never bleeds into the new image.
rm -rf "${APPDIR}"
mkdir -p "${APPDIR}/usr/bin" \
         "${APPDIR}/usr/share/applications" \
         "${APPDIR}/usr/share/icons/hicolor/scalable/apps"

# Binary + desktop entry + icon.
install -Dm755 target/release/melete-app "${APPDIR}/usr/bin/melete-app"
install -Dm644 resources/app.melete.desktop \
    "${APPDIR}/usr/share/applications/app.melete.desktop"
install -Dm644 resources/icons/app.melete.svg \
    "${APPDIR}/usr/share/icons/hicolor/scalable/apps/app.melete.svg"

# linuxdeploy wants the top-level .desktop + icon mirrored at AppDir/
# root too. AppRun is auto-generated by the linuxdeploy tool.
install -Dm644 resources/app.melete.desktop "${APPDIR}/app.melete.desktop"
install -Dm644 resources/icons/app.melete.svg "${APPDIR}/app.melete.svg"

# Fetch linuxdeploy + the GTK plugin into a tools dir so concurrent
# CI runs don't trample each other's caches.
TOOLS="${DIST}/tools"
mkdir -p "${TOOLS}"

LD_URL="https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${ARCH}.AppImage"
LD_GTK_URL="https://raw.githubusercontent.com/linuxdeploy/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh"

if [[ ! -x "${TOOLS}/linuxdeploy-${ARCH}.AppImage" ]]; then
    curl -fsSL "${LD_URL}" -o "${TOOLS}/linuxdeploy-${ARCH}.AppImage"
    chmod +x "${TOOLS}/linuxdeploy-${ARCH}.AppImage"
fi
if [[ ! -x "${TOOLS}/linuxdeploy-plugin-gtk.sh" ]]; then
    curl -fsSL "${LD_GTK_URL}" -o "${TOOLS}/linuxdeploy-plugin-gtk.sh"
    chmod +x "${TOOLS}/linuxdeploy-plugin-gtk.sh"
fi

# linuxdeploy itself ships as an AppImage; on CI runners without
# FUSE we extract + run from disk. APPIMAGE_EXTRACT_AND_RUN handles
# both cases — local + CI — without conditionals.
export APPIMAGE_EXTRACT_AND_RUN=1
export PATH="${TOOLS}:${PATH}"
export VERSION

# linuxdeploy walks the desktop entry → finds the Exec binary →
# resolves shared lib deps via ldd → copies them into AppDir/usr/lib.
# The GTK plugin then drops in GIO modules + GdkPixbuf loader cache
# so file dialogs, SVG decoding, and theme lookup work in the bundle.
"${TOOLS}/linuxdeploy-${ARCH}.AppImage" \
    --appdir "${APPDIR}" \
    --plugin gtk \
    --desktop-file "${APPDIR}/app.melete.desktop" \
    --icon-file "${APPDIR}/app.melete.svg" \
    --output appimage

# linuxdeploy emits to the cwd with a generated name; rename to our
# stable convention.
mv -v "Melete-${ARCH}.AppImage" "${DIST}/Melete-${VERSION}-${ARCH}.AppImage" 2>/dev/null \
    || mv -v "$(ls -t Melete*.AppImage | head -1)" "${DIST}/Melete-${VERSION}-${ARCH}.AppImage"

echo "[appimage] built ${DIST}/Melete-${VERSION}-${ARCH}.AppImage"
